-- =============================================================================
-- FIX: ADD PRIMARY KEYS TO ALL SUPABASE TABLES
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor > New query > Run)
-- =============================================================================

-- 1. FIX 'articles' TABLE
DO $$
BEGIN
    -- Add 'id' column if it does not exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'articles' AND column_name = 'id'
    ) THEN
        ALTER TABLE public.articles ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    -- Add PRIMARY KEY constraint if not present
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_schema = 'public' AND constraint_type = 'PRIMARY KEY' AND table_name = 'articles'
    ) THEN
        ALTER TABLE public.articles ADD PRIMARY KEY (id);
    END IF;
END $$;


-- 2. FIX 'feedback' TABLE
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'feedback' AND column_name = 'id'
    ) THEN
        ALTER TABLE public.feedback ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_schema = 'public' AND constraint_type = 'PRIMARY KEY' AND table_name = 'feedback'
    ) THEN
        ALTER TABLE public.feedback ADD PRIMARY KEY (id);
    END IF;
END $$;


-- 3. FIX 'collaborations' TABLE
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'collaborations' AND column_name = 'id'
    ) THEN
        ALTER TABLE public.collaborations ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_schema = 'public' AND constraint_type = 'PRIMARY KEY' AND table_name = 'collaborations'
    ) THEN
        ALTER TABLE public.collaborations ADD PRIMARY KEY (id);
    END IF;
END $$;


-- 4. FIX 'certifications' TABLE
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'certifications' AND column_name = 'id'
    ) THEN
        ALTER TABLE public.certifications ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_schema = 'public' AND constraint_type = 'PRIMARY KEY' AND table_name = 'certifications'
    ) THEN
        ALTER TABLE public.certifications ADD PRIMARY KEY (id);
    END IF;
END $$;


-- 5. FIX 'comments' TABLE
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'comments' AND column_name = 'id'
    ) THEN
        ALTER TABLE public.comments ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_schema = 'public' AND constraint_type = 'PRIMARY KEY' AND table_name = 'comments'
    ) THEN
        ALTER TABLE public.comments ADD PRIMARY KEY (id);
    END IF;
END $$;


-- 6. FIX 'categories' TABLE
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'categories' AND column_name = 'id'
    ) THEN
        ALTER TABLE public.categories ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_schema = 'public' AND constraint_type = 'PRIMARY KEY' AND table_name = 'categories'
    ) THEN
        ALTER TABLE public.categories ADD PRIMARY KEY (id);
    END IF;
END $$;


-- 7. FIX 'site_stats' TABLE
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_schema = 'public' AND constraint_type = 'PRIMARY KEY' AND table_name = 'site_stats'
    ) THEN
        ALTER TABLE public.site_stats ADD PRIMARY KEY (key);
    END IF;
END $$;
