-- =============================================================================
-- SUPABASE DATABASE SETUP & FULL CRUD POLICY SCRIPT FOR FINANCIAL BLOG PLATFORM
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor > New query > Run)
-- =============================================================================

-- 1. Create 'articles' Table
CREATE TABLE IF NOT EXISTS public.articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    excerpt TEXT,
    category TEXT NOT NULL,
    thumbnail_url TEXT,
    author TEXT DEFAULT 'Tushar Singh, CFA',
    read_time TEXT DEFAULT '5 min read',
    views INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    is_trending INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Safely add columns if 'articles' table already exists
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS likes INTEGER DEFAULT 0;
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS is_trending INTEGER DEFAULT 0;
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS read_time TEXT DEFAULT '5 min read';
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS author TEXT DEFAULT 'Tushar Singh, CFA';

-- 2. Create 'categories' Table (for Dynamic Insight Topics)
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create 'collaborations' Table (for "Let's Collaborate" section)
CREATE TABLE IF NOT EXISTS public.collaborations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    project_type TEXT DEFAULT 'Financial Modeling & Valuation',
    message TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create 'feedback' Table (for "Article Feedback" rating section)
CREATE TABLE IF NOT EXISTS public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating INTEGER DEFAULT 5,
    suggestion TEXT NOT NULL,
    name TEXT DEFAULT 'Anonymous Reader',
    email TEXT,
    article_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create 'comments' Table (for Article Engagement Live Comments)
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    author TEXT DEFAULT 'Anonymous Analyst',
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create 'certifications' Table (for Licenses & Certifications)
CREATE TABLE IF NOT EXISTS public.certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    issuer TEXT NOT NULL,
    dates TEXT,
    icon TEXT DEFAULT 'Award',
    article_id BIGINT,
    article_title TEXT,
    article_content TEXT,
    insights TEXT,
    excel_url TEXT,
    excel_name TEXT,
    cert_doc_url TEXT,
    cert_doc_name TEXT,
    status TEXT DEFAULT 'Verified',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Create 'site_stats' Table (for Visitor & Global Click Counters)
CREATE TABLE IF NOT EXISTS public.site_stats (
    key TEXT PRIMARY KEY,
    value INTEGER DEFAULT 0
);

-- =============================================================================
-- 8. Enable Row Level Security (RLS) & Grant Full Permissions
-- =============================================================================

ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collaborations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_stats ENABLE ROW LEVEL SECURITY;

-- Clean existing policies to prevent conflicts
DROP POLICY IF EXISTS "Allow public all articles" ON public.articles;
DROP POLICY IF EXISTS "Allow public read articles" ON public.articles;
DROP POLICY IF EXISTS "Allow public update articles likes" ON public.articles;
DROP POLICY IF EXISTS "Allow public insert articles" ON public.articles;
DROP POLICY IF EXISTS "Allow public delete articles" ON public.articles;

DROP POLICY IF EXISTS "Allow public all categories" ON public.categories;
DROP POLICY IF EXISTS "Allow public all collaborations" ON public.collaborations;
DROP POLICY IF EXISTS "Allow public all feedback" ON public.feedback;
DROP POLICY IF EXISTS "Allow public all comments" ON public.comments;
DROP POLICY IF EXISTS "Allow public all certifications" ON public.certifications;
DROP POLICY IF EXISTS "Allow public all site_stats" ON public.site_stats;

-- Create Unrestricted CRUD Policies for All Tables
CREATE POLICY "Allow public all articles" ON public.articles 
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public all categories" ON public.categories 
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public all collaborations" ON public.collaborations 
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public all feedback" ON public.feedback 
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public all comments" ON public.comments 
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public all certifications" ON public.certifications 
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public all site_stats" ON public.site_stats 
    FOR ALL USING (true) WITH CHECK (true);

-- =============================================================================
-- 9. Seed Initial Default Data (Safe with ON CONFLICT)
-- =============================================================================

INSERT INTO public.categories (name) VALUES 
('Financial Valuation'),
('Macroeconomics'),
('DeFi 3.0'),
('SaaS & Tech'),
('Stocks'),
('Wealth Management')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.site_stats (key, value) VALUES 
('total_visits', 150),
('total_clicks', 0)
ON CONFLICT (key) DO UPDATE SET key = EXCLUDED.key;
